version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.9.3
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xmx256m -Xms256m
      ELASTIC_PASSWORD: changeme
    ports:
      - 9200:9200
    volumes:
      - elastic-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.9.3
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
  
volumes:
  elastic-data:
    driver: local