server.name: kibana
server.host: 0.0.0.0
elasticsearch.hosts: [ "http://elasticsearch:9200" ]

elasticsearch.username: elastic
elasticsearch.password: changeme
kibana.defaultAppId: "dashboard/your-dashboard-id"
newsfeed.enabled: false

elastalert-kibana-plugin.serverHost: elastalert
elastalert-kibana-plugin.serverPort: 3030